name: Tinta del Dia - TDD
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94766606669873
title: Tinta del Dia - de Jose Luis Alfinger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8235282450914383
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
