name: Tinta del Dia - TDD
favicon: null
layout_spectrum: 0.95761
typography_spectrum: 0.43707
title: Tinta del Dia - de Jose Luis Alfinger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#349dd6'
    - '#2b2e1d'
    - '#126eb9'
    - '#635f18'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
